### PR TITLE
Setting up of views

### PR DESCRIPTION
**Pull request by dehuks**

### CODE REVIEW

**Comment by dehuks** [comment]
I need to know all the views that we need to kickstart

**Comment by lewis-andy** [comment]
This is my opinion regarding the expected reviews
- contact view
- dashboard view
- garbage collection request
- waste type

**Review by lewis-andy — APPROVED** [review]
we will add more views this is the start

**Review by Levi-LMN — COMMENTED** [review]
This is a more comprehensive approach that may we may not necessarily add now:

## 1. Login & Onboarding View
- **Login/Signup Page**: Options to log in with an email, social accounts, or phone number.
- **Onboarding Carousel**: Quick slides to explain the app’s purpose, features, and benefits for users and communities.

## 2. Home/Dashboard View
- **Waste Collection Status**: Shows current status of waste bins (e.g., "50% full", "Full", "Empty").
- **Nearest Bins Map**: Map showing locations of nearby smart bins with real-time statuses.
- **Daily Updates**: Notifications of scheduled pickups, bin full alerts, or collection delays.
- **Alerts and Reminders**: Notifications to remind users of specific waste segregation guidelines or days for pickup.

## 3. Map View
- **Real-Time Bin Tracking**: Shows nearby bins on a map, their fill status, last collection time, and location-specific details.
- **Route Optimization**: For garbage collectors, the optimized path to collect bins in an efficient manner.
- **Search Bar**: Search functionality to find bins by location or bin type (e.g., recycling, hazardous waste).

## 4. Bin Details View
- **Bin Information**: Shows data for a specific bin, like fill level, last emptied date, and location.
- **Request Pickup Button**: For residents to request an early pickup if a bin is full.
- **Report Issue Button**: For users to report problems, such as damaged bins or missed pickups.

## 5. Collection Scheduling & Reminders View
- **Pickup Scheduling**: Option for users to schedule additional pickups if necessary.
- **Reminder Notifications**: Alerts for designated collection days and reminders to place bins outside.
- **Waste Segregation Reminders**: Tips and guides on segregating waste effectively.

## 6. Report Issue View
- **Issue Form**: Options to report various issues (e.g., “Bin overflowing,” “Bin damaged,” “Collection missed”).
- **Photo Upload**: Users can upload a photo to illustrate the issue.
- **Issue Tracking**: Track the progress of the reported issue and its resolution status.

## 7. Profile & Settings View
- **User Information**: Profile details like address, contact information, and preferences.
- **Preferences**: Option to manage notification settings, preferred pickup days, etc.
- **Address Management**: Option to add or edit addresses if the user has multiple properties.

## 8. Waste Analytics View (for Admin/Collectors)
- **Analytics Dashboard**: Data on waste collection patterns, volume metrics, etc.
- **Collection Insights**: Trends in waste collection, areas with high waste volumes, etc.
- **Maintenance Alerts**: Notifications for bins needing repairs or replacements.

**Review by Cypherkid — APPROVED** [review]

**Pull request merged**
